// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"YEP_RegionRestrictions","status":true,"description":"v1.04 Use regions to block out Events and/or the player from\nbeing able to venture into those spots.","parameters":{"Player Restrict":"0","Event Restrict":"1","All Restrict":"0","Player Allow":"0","Event Allow":"0","All Allow":"0"}},
{"name":"YEP_X_VehicleRestrict","status":true,"description":"v1.01 (Req YEP_RegionRestrictions.js) This plugin allows you\nto control where vehicles can move and can land.","parameters":{"---Boat---":"","Boat Restrict":"0","Boat Allow":"0","Boat Land":"0","---Ship---":"","Ship Restrict":"0","Ship Allow":"0","Ship Land":"2","---Airship---":"","Airship Restrict":"0","Airship Allow":"0","Airship Land":"0"}},
{"name":"GALV_PictureAnims","status":true,"description":"(v.1.3) Play database animations on pictures made with \"Show Picture\"","parameters":{"":""}}
];
